###################################
##### Bungee Chat Plus Config #####
###################################
# Always usable variables:
# %player%, %name% - Player display name
# %message% - Message being sent
# %server% - Server name
# %type% - Local or global chat. Can be configured using varGlobalChat and varLocalChat
# %forced% - Whether the player is forced or not. Can be configured using varForcedGlobal and varNotForced
# %ping% - The player's current ping
#
# Variables that can be used if BungeeChatPlus is installed on the Bukkit/Spigot server
# %tabName% - Player tab name
# %displayName% - Player display name
#
# Variables that can be user if Vault is installed along with BungeeChatPlus on the Bukkit/Spigot server
# %group% - Player group
# %prefix% - Player prefix
# %suffix% - Player suffix
#
# The format used for all chat messages
chatFormat: "&a[&9%type%%forced%&a] [&9%server%&a] [&9%prefix%&a] &9[suggest=@%name% ][hover=%name%]%tabName%[/hover][/suggest]&a:&r %message%"
# If connection with the bukkitbridge fails, it will still send the message with the backup format.
# YOU CAN ONLY USE 'ALWAYS USABLE VARIABLES' IN THIS MESSAGE
backupChatFormat: "&a[&cERR&a] [&9%type%%forced%&a] [&9%server%&a] &9%name%&a:&r %message%"

varGlobalChat: "Global"
varLocalChat: "Local"
varForcedGlobal: "-Forced"
varNotForced: ""
localChatMessage: "&7You are now listening to local chat."
globalChatMessage: "&7You are now listening to global chat."
toggleChatEnabled: true
toggleChatCommandAliases: ['togglechat', 'chattoggle']
globalChatCommandEnabled: false
globalChatCommandAliases: ['global', 'g']
localChatCommandEnabled: false
localChatCommandAliases: ['local', 'l']

###################################
#####    Private Messaging    #####
###################################
pmEnabled: true
pmSend: "&b[suggest=/w %target-name% ]You -> [%target-server%] %target-name%[/suggest]&f > [i]%message%[/i]"
pmReceive: "&b[suggest=/w %sender-name% ][%sender-server%] %sender-name% -> me[/suggest] &f> [i]%message%[/i]"
pmUnknownTarget: "&c%target% is not on the server"
pmPlaySound: true
pmSound: ORB_PICKUP
pmCommandAliases: ['w', 'msg', 'message', 'tell', 'whisper', 'pm']
pmReplyCommandAliases: ['reply', 'r']
# Conversations - PMs but with no other chat
pmConversationCommandAliases: ['chat', 'conversation']
pmConversationStartMessage: "&aYou started a conversation with %target%. All your chat messages will go directly to %target%."
pmConversationEndMessage: "&cYour conversation with %target% is over. Chat works as normal again."

###################################
#####    Mentioning Players   #####
###################################
enableTaggingPlayers: true
taggedPlayer: "[color=gold][suggest=/w ${name}]@${name}[/suggest][/color]"
playSoundToTaggedPlayer: true
playerTaggedSound: ORB_PICKUP

###################################
#####      Player Muting      #####
###################################
muteEnabled: true
muteMessage: "&cYou have been muted for %reason% until %duration%"
mutePardonMessage: "&cYou have been unmuted"
muteDenyMessage: "&cYou are muted for %reason% until %duration%. for further assistance pm a Moderator."
muteSuccess: "&7%target% has been muted for %reason% until %duration%"
muteUnmuted: "&7%target% has been unmuted"
muteAlreadyMuted: "&7%target% is already muted for %reason% until %duration%"
muteUnmuteFail: "&7%target% is not muted"
muteCommandAliases: ['mute', 'bungeemute']
muteTempMuteCommandAliases: ['tempmute', 'bungeetempmute']
muteUnmuteCommandAliases: ['unmute', 'bungeeunmute']
muteListCommandAliases: ['mutelist', 'bungeemutelist', 'listmuted', 'bungeelistmuted']

###################################
#####    Player Silencing     #####
###################################
silenceEnabled: true
silenced: "&cYou are silenced. Do [suggest=/silence]/silence[/suggest] to be unsilenced"
silencePlayer: "&7%target%'s chat has been silenced"
unsilencePlayer: "&7%target%'s chat has been unsilenced"
silenceCommandAliases: ['silence', 'silencechat']
unslienceCommandAliases: ['unsilence', 'unsilencechat']

###################################
#####      Player Ignore      #####
###################################
ignoreEnabled: true
ignored: "&c%target% has ignored you"
ignoreSuccess: "&7You are now ignoring %target%"
ignoreUnignore: "&7You are no longer ignoring %target%"
ignoreCommandAliases: ['ignore', 'ignoreplayer']

###################################
#####     Player Filtering    #####
###################################
filterEnabled: true
filterAdd: "&6%filter% &7has been added to your filters"
filterRemove: "&6%filter% &7has been removed from your filters"
filterAlreadyFiltered: "&6%filter% &cis already filtered"
filterNotFiltered: "&6%filter% &cis not on your filter list"
filterNoFilters: "&cYou do not have any filters"
filterCommandAliases: ['filter', 'filterchat']
filterListCommandAliases: ['filterlist', 'filterchatlist']
# A list of things that players cannot filter (filters matching these will be able to be added, but they will have no effect)
filterBlacklist: ['Forced']

###################################
#####        Anti-Spam        #####
###################################
antiSpamEnabled: true
# antiSpamMuteTime is not implemented yet.
antiSpamMuteTime: 60
antiSpamDenyMessage: "&cYou have sent to many messages. You must wait 1 minute before sending messages again."

antiCapsEnabled: true
antiCapsActivationLength: 3
antiCapsActivationPercentage: 50
antiCapsAutoLowercase: true
antiCapsMessage: "&bPlease refrain from using caps in chat"

antiSwearEnabled: true
antiSwearMessage: "&bPlease refrain from swearing in chat"
antiSwearList: ['fuck', 'shit', 'addSomethingElseAlready']

###################################
#####           Misc          #####
###################################
# If enabled chat messaged are written into logs in the BungeeChatPlus directory
logChat: true
logCommands: true
consoleName: "&4CONSOLE"
bcpCommandAliases: ['bcp', 'bungeechatplus']
reloadCommandAliases: ['bcpreload', 'bungeechatplusreload']
unknownTarget: "&7%target% is not on the server"
commandDisabled: "&cThe command &6%command% &cis disabled"
replaceVarError: "&cError replacing variables. Sending as is. Have you installed BungeeChatPlus on this server?"
internalError: "&cAn internal error occurred while processing your chat message."
alwaysGlobalChat: true
allowBBCodeInVariables: false
excludeServers: []
dontTouch:
  debug: false
  version:
    seriouslyThisWillEraseYourConfig: '1.8.1'

###################################
#####          Regex          #####
###################################
regex:
# make any pasted links clickable for convenience
    - search: '(?<link>(?:(https?)://)?([-\w_\.]{2,}\.[a-z]{2,4})(/\S*)?)'
      replace: "[url]${link}[/url]"
# shows link target in tooltip for security reasons (only if link target differs from shown text)
    - search: '(?i)\[(?:url|command)=(?<cmd>(?:(?:[^]\[]*)\[(?:[^]\[]*)\])*(?:[^]\[]*))\]'
      replace: "[hover=&b${cmd}]$0"
    - search: '(?i)\[/(?:url|command)\]'
      replace: "$0[/hover]"
# if players write commands in chat like ./command, make them clickable + remove the dot
    - search: '(?i)^\.(?<cmd>/.{2,})'
      replace: "[suggest]${cmd}[/suggest]"
# some smileys
    - search: '--->'
      replace: "\u21DB"
    - search: '<---'
      replace: "\u21DA"
    - search: '-->'
      replace: "\u21D2"
    - search: '<--'
      replace: "\u21D0"
    - search: '->'
      replace: "\u2192"
    - search: '<-'
      replace: "\u2190"
    - search: '\(o\)|\(O\)|\(time\)'
      replace: "\u231A"
    - search: '\(rain\)'
      replace: "\u2602"
    - search: '\(sun\)'
      replace: "\u2600"
    - search: '<3'
      replace: "\u2764"
# underline clickable things
    - search: '(?i)(?=(\[(?:url|command|suggest)(?:=(?<cmd>(?:(?:[^]\[]*)\[(?:[^]\[]*)\])*(?:[^]\[]*)))?\]))'
      replace: "[u]"
    - search: '(?i)\[/(?:url|command|suggest)\]'
      replace: "$0[/u]"