name: BungeeChatPlus
main: net.willsr71.bungeechatplus.bukkit.BungeeChatPlusBukkit
version: %VERSION%
description: A capable chat plugin for bungee
author: Willsr71
website: https://willsr71.net/
commands:
  bcp:
    description: Core command for BungeeChatPlus
    usage: /bcp <args>
    aliases: [bcp, bungeechatplus]
permissions:
  bungeechatplus.reload:
    desfault: op
    description: The ability to reload plugin configs
  bungeechatplus.mute.mute:
    default: op
    description: Ability to permanently mute players
  bungeechatplus.mute.tempmute:
    default: op
    description: Ability to temporarily mute players
  bungeechatplus.mute.unmute:
    default: op
    description: Ability to unmute players
  bungeechatplus.silence.others:
    default: op
    description: Ability to silence and unsilence players' chat
  bungeechatplus.forceglobalchat:
    default: op
    description: Players with this permission force their chat messages to all players, regardless of that player being on local or global chat, useful for staff work
  bungeechatplus.ignorecapsprevention:
    default: op
    description: Ignore caps filtering
  bungeechatplus.togglechat.others:
    default: op
    description: Ability to toggle other's local/global chat
  bungeechatplus.chat.color:
    desfault: op
    description: The ability to usee color codes in chat
  bungeechatplus.chat.bbcode:
    desfault: op
    description: The ability to use BBcode in chat